title: OptimizationConfig
type: object
properties:
  iterations:
    type: integer
  epsilon:
    type: number
  strategy:
    type: string
    description: "Optimization Strategy"
    enum:
      - admin
      - editor
      - viewer
  model:
    # References another file and a specific definition inside it
    $ref: "models.yaml#/$defs/BaseModel"
required:
  - strategy
  - model
